# Generated by go2rpm 1
%bcond_without check

# https://github.com/timberio/go-datemath
%global goipath         github.com/timberio/go-datemath
%global commit          85899cbcaa93928307db1492018258c9532df8e1

%gometa

%global common_description %{expand:
Go library for parsing Elasticsearch datemath expressions.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Go library for parsing Elasticsearch datemath expressions

License:        ISC
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Jun 25 19:42:56 CEST 2020 Andreas Gerstmayr <agerstmayr@redhat.com> - 0-0.1.20200625git85899cb
- Initial package

